### ISSUE TITLE
Document how to control the size of the tag cloud

### ISSUE THREAD

**Issue by sashamitrovich** [grtjn/d3-cloud-ng#10]
Example
`<d3-cloud words="ctrl.words" padding="0" slope-base="10" slope-factor="70" rotate="ctrl.noRotate(word)" events="ctrl.cloudEvents"></d3-cloud>
    </div>`

**Comment by grtjn** [comment]
I notice I have both details in the README as well as on github.io. The README should point to github.io, and the github.io should contain ref docs. The quickstart example should at least point to the reference and mention there are extra options on the directive..
