### ISSUE TITLE
Cloud update after words[] updated

### ISSUE THREAD

**Issue by prowave** [grtjn/d3-cloud-ng#13]
After I push() name/score pairs to my words array, my cloud doesn't update to reflect all the words in the array.  Is there 2-way data binding between the directive and the underlying words array?

I have verified that the initial name/score pairs appear in the cloud, but anything I push after that doesn't show and I can debug the underlying array to see the original words and the newly pushed words.

My use case should be pretty simple where I am making an ajax call to get the list of words, and on the success promise I am updating the words[].  This obviously happens after the initial directive has rendered and loaded.

Thanks for any help you can provide.

**Comment by grtjn** [comment]
I suspect it is because I am using a shallow watch, not a deep one. Let me run a test with that. In the mean time, recreate the words array, rather than appending to it..

**Comment by grtjn** [comment]
@prowave I pushed a fix, and cut a new release for it. You can pull it in with `bower update d3-cloud-ng`.

**Comment by prowave** [comment]
Thank you

David Webb
