### ISSUE TITLE
Cannot display multiple clouds on a single page

### ISSUE THREAD

**Issue by abedegno** [grtjn/d3-cloud-ng#6]
Multiple <d3-cloud> directives can not be used within the same partial as a select is made on the non-unique .cloud css cloud.

**Comment by grtjn** [comment]
Whoops, glanced over that. I'll take a look asap..

**Comment by grtjn** [comment]
Interestingly, having two d3-clouds on one page works without issues for me. What kind of side-effects are you observing? Maybe you can provide some more details on what you did?

**Comment by grtjn** [comment]
Wait, with a heading between them you see the second one is not shown under the heading, but above..
