### ISSUE TITLE
Latest version of d3 breaks d3-cloud-nd

### ISSUE THREAD

**Issue by sashamitrovich** [grtjn/d3-cloud-ng#9]
Use
"d3": "~3.5.16"
for a quick fix.

**Comment by grtjn** [comment]
Unfortunate these kind of breaking changes. Can you provide the error message you were getting? I'd like to dig a little deeper to whether this is just a regression of d3(-cloud), or maybe an api change..

**Comment by sashamitrovich** [comment]
angular.js:12798 TypeError: Cannot read property 'category20' of undefined
    at Dispatch.r (d3-cloud-ng.min.js:1)
    at Dispatch.end (d3.layout.cloud.js:486)
    at step (d3.layout.cloud.js:76)
    at Object.cloud.start (d3.layout.cloud.js:53)
    at Scope.t.createCloud (d3-cloud-ng.min.js:1)
    at d3-cloud-ng.min.js:1
    at Scope.$digest (angular.js:16218)
    at Scope.$apply (angular.js:16482)
    at done (angular.js:10862)
    at completeRequest (angular.js:11060)

undefined would be d3.scale

**Comment by grtjn** [comment]
This seems to be a similar issue. I need to rethink whether to fix on v3 for now, or move forward to v4. Or maybe there is a way to run compatible with both?

http://stackoverflow.com/questions/38536456/angular-nvd3-gives-various-errors-saying-that-d3-scale-is-undefined

**Comment by grtjn** [comment]
Looking into it in more detail, it seems `d3.scale.category20()` was renamed to `d3.schemeCategory20()`. Should be relatively simple to use `(d3.schemeCategory20 ? d3.schemeCategory20() : d3.scale.category20())`. That would allow supporting both d3 v3 and v4..

**Comment by grtjn** [comment]
On further testing above change was insufficient. d3.on does no longer take a hash with multiple event callbacks, and even if you fix that, it still doesn't paint anything. I'll open a separate ticket for d3 v4 support..

**Comment by grtjn** [comment]
Solved via bower.json.
